### ISSUE TITLE
openstack CLI docker tty

### ISSUE THREAD

**Issue by Nils98Ar** [osism/ansible-collection-services#1265]
The `-t` leads to adding a carriage return to the output when running the `openstack` command interactively.
Why would you want to run the openstack commands in the container with tty?

Because of that we need a `tr -d "\r"` before working with the output all the time.

https://github.com/osism/ansible-collection-services/blob/2a9f8a404547e98ad7ee5cc2628018bb59836a25/roles/openstackclient/templates/openstack.j2#L13C12-L13C12

See https://github.com/moby/moby/issues/8513#issuecomment-216191236.

**Comment by berendt** [comment]
At the moment we use `-it` everywhere when we run a command inside a container. There is no specific reason, it has worked so far. Feel free to change it where required.

**Comment by osfrickler** [comment]
Removing the `-it` globally breaks interactive clients and also terminal width detection with the `--fit-width` option for the openstack client. You can either add `</dev/null` to the client invocation or we can add a fix like proposed in https://github.com/osism/ansible-collection-services/pull/1268.
