### ISSUE TITLE
[Netbox] Add option to install additional python packages required by plugins or scripts into netbox containers

### ISSUE THREAD

**Issue by matofeder** [osism/ansible-collection-services#1572]
Netbox plugins and scripts could require the installation of additional Python packages that are not in the Netbox virtual environment (see e.g. https://github.com/netbox-community/netbox-napalm-plugin?tab=readme-ov-file#installation) 

The recommended way how to achieve an installation of these packages in the netbox-docker project is via local_requirements.txt or plugin_requirements.txt, see https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins#step-2---modify-new-files

Add an option to install additional Python packages required by plugins or scripts into the OSISM Netbox role

**Comment by berendt** [comment]
We'll not support this via the Ansible role. The container images are immutable. Please add additional plugins here: https://github.com/osism/container-images/blob/main/netbox/requirements.txt
