### ISSUE TITLE
openldap: use build-xxx tag for all univention images

### ISSUE THREAD

**Issue by berendt** [osism/ansible-collection-services#271]
Currently, a build-21741 is used for the univention-upx-container-umc-server. As with the other images, an exerpimental or latest tag should be used by default.

Currently there is no experimental or latest tag for this image on Quay.io.

**Comment by Ferenc-** [comment]
The plan is to replace all these tags with  build ID tags( `build-XXXX`). I will make it a priority from tomorrow.

**Comment by berendt** [comment]
Also works. Then please replace all exerpimental tags with a `build-xxx` tag.

**Comment by Ferenc-** [comment]
Now we use build-xxx tags everywhere, the 2 umc image shares the same, openldap has one separate, and udm-rest has one separate.

**Comment by Ferenc-** [comment]
https://github.com/osism/ansible-collection-services/pull/277
