### ISSUE TITLE
openldap: check use of 1.2.3.4 as value for ldap/server/ip

### ISSUE THREAD

**Issue by berendt** [osism/ansible-collection-services#272]
Currently, the static value 1.2.3.4 is used for ldap/server/ip in various places. Is this correct?

**Comment by berendt** [comment]
@Ferenc- Please take care of this and accept my invite to the OSISM organisation.

**Comment by Ferenc-** [comment]
I will check this, this value might not be needed.

**Comment by Ferenc-** [comment]
To be removed in https://github.com/osism/ansible-collection-services/pull/278
