### ISSUE TITLE
openldap: use of static URL in openldap.env.j2

### ISSUE THREAD

**Issue by berendt** [osism/ansible-collection-services#273]
```
# A comma separated list of trusted SAML2 Service Provider URLs:
SERVICE_PROVIDERS=https://ucs-1788.univention-organization.intranet/univention/saml/metadata
```

Should this be configurable?

**Comment by berendt** [comment]
@Ferenc- Please take care of this and accept my invite to the OSISM organisation.

**Comment by Ferenc-** [comment]
I will check this, we might not need this at all.

**Comment by Ferenc-** [comment]
Sorry, the PR, had a faulty tag the #273 meant to be #272.
Could you please reopen this? This still needs some attention, I am on it.

**Comment by Ferenc-** [comment]
https://github.com/osism/ansible-collection-services/pull/284 should mitigate this for now.
