### ISSUE TITLE
Removing from the UCS role

### ISSUE THREAD

**Issue by berendt** [osism/ansible-collection-services#276]
@Ferenc- Now that we have the openldap role with the UCM/UDM services, we can remove the UCS role, right?

**Comment by Ferenc-** [comment]
Could you give me more specifics, which code would be a good candidate for removal?

**Comment by berendt** [comment]
This one: https://github.com/osism/ansible-collection-services/tree/master/roles/ucs

**Comment by Ferenc-** [comment]
Yes, that can be removed. Should I do it?

**Comment by berendt** [comment]
That would be good, yes.
