### ISSUE TITLE
Connect Web interfaces to IAM via OIDC

### ISSUE THREAD

**Issue by Ferenc-** [osism/ansible-collection-services#286]
Connect the Web interfaces of the following services via OIDC:

* [ ] ARA
* [ ] Ceph dashboard
* [ ] Cockpit
* [ ] Grafana
* [ ] Heimdall
* [ ] Jenkins
* [ ] Kibana
* [ ] Netbox
* [ ] Patchman
* [ ] Prometheus
* [ ] Rally
* [ ] Rundeck
* [ ] phpMyAdmin
* [ ] UMC
* [ ] Zabbix

**Comment by berendt** [comment]
I'm closing because nothing else has happened here for 2 years.
