### ISSUE TITLE
docker_allow_restart breaks osism-generic bootstrap

### ISSUE THREAD

**Issue by maliblatt** [osism/ansible-collection-services#303]
since the bootstrap allows the docker daemon to restart after creating /etc/docker/daemon.json on the manager itself, the deployment breaks because the manager_osism-ansible_1 container will be also restarted and the bootstrap kills itself.

What was the reason to restart the docker daemon in that place? from documentation after bootstrap there is a planned reboot, so from my point of view there is no need to restart the docker here.

https://github.com/osism/ansible-collection-services/blob/a06ff300d36f10cd3825908832b7ee8fe6d75912/roles/docker/handlers/main.yml#L2-L7

**Comment by berendt** [comment]
@maliblatt https://github.com/osism/cfg-generics/pull/155 is also required. Docker service on the manager can then be restarted via osism-manager docker.
