### ISSUE TITLE
homer: Light/Default modes makes buttons unreadable when hovering

### ISSUE THREAD

**Issue by berendt** [osism/ansible-collection-services#353]

**Comment by berendt** [comment]
@osfrickler Please add a screenshot.

**Comment by osfrickler** [comment]
![Screenshot from 2021-11-03 12-28-08](https://user-images.githubusercontent.com/86402919/140052966-4211e8ec-4d1b-461a-ab58-5c43d5a9f5eb.png

![Screenshot from 2021-11-03 12-28-42](https://user-images.githubusercontent.com/86402919/140052981-1f37691d-e502-4fc0-85a5-7aff5c5426c0.png)
)

**Comment by tibeer** [comment]
![image](https://user-images.githubusercontent.com/39375770/140264312-4a67b429-e1c9-4d77-8df3-1977e03cb60a.png)

**Comment by tibeer** [comment]
Changed the font color to black.
