### ISSUE TITLE
osism.services.manager Start/enable manager service fails because of failing authorization while accessing quay.io/library/

### ISSUE THREAD

**Issue by costelter** [osism/ansible-collection-services#711]
While redeploying our oldest dev env I stumbled upon the failure of starting the docker-compose@manager.service:

    TASK [osism.services.manager : Start/enable manager service] *******************
    fatal: [manager1-dev1-az0.pco.ps-intern.de]: FAILED! => {"changed": false, "msg": "Unable to start service docker-compose@manager: Job for docker-compose@manager.service failed because the control process exited with error code.\nSee \"systemctl status docker-compose@manager.service\" and \"journalctl -xe\" for details.\n"}

It seems that redis and mariadb are no longer coming from quay.io/library/ are no longer available to the public.

```
root@manager1-dev1-az0:/opt/manager# docker pull quay.io/library/mariadb:10.8.3
Error response from daemon: unauthorized: access to the requested resource is not authorized
root@manager1-dev1-az0:/opt/manager# docker pull quay.io/library/redis:7.0.0-alpine
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

**Comment by berendt** [comment]
Which version of the manager? Latest and greatest? The images are on docker hub and not quay.io.

**Comment by costelter** [comment]
Yessir. configuration.yml states latest:

--- cut --- 
ceph_version: pacific
manager_version: latest
openstack_version: xena
--- cut ---

**Comment by costelter** [comment]
So. If docker hub should be the source, then my environments/configuration.yml is just outdated?

environments/configuration.yml:
ceph_docker_registry: quay.io
docker_registry_ansible: quay.io
docker_registry_service: quay.io

**Comment by berendt** [comment]
That's wrong, yes. Check https://github.com/osism/testbed/blob/main/environments/configuration.yml#L18-L21.

**Comment by costelter** [comment]
Thanks for the help! Now it works as expected.
