### ISSUE TITLE
Nexus: docker-compose.yml cannot use variable nexus_host for port definitions

### ISSUE THREAD

**Issue by grawert** [osism/ansible-collection-services#718]
The `nexus_host` variable can contain DNS name. The DNS name cannot be used to define ports in `docker-compose.yml`. The variable need to be converted to an IP address first.

https://github.com/osism/ansible-collection-services/blob/main/roles/nexus/templates/docker-compose.yml.j2#L11-L21

**Comment by grawert** [comment]
But still, if someone sets `nexus_host: localhost` the `docker-compose.yml` has invalid port definitions. This will be quite difficult to discover by a user. It would be good to check for IP. If IP is not set, try to resolve the hostname to an IP address and use this IP in the `docker-compose.yml` for port entries.

**Comment by berendt** [comment]
It must be an IP address, yes. Otherwise it does not work. But that is the case everywhere. Not sure if we should support wrong input? I think it makes more sense to mention in the documentation that it must be an IP address.
