### ISSUE TITLE
Replace hddtemp role

### ISSUE THREAD

**Issue by osfrickler** [osism/ansible-collection-services#822]
> After doing some research, hddtemp appears to be abandoned and debian dropped it, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002484. The recommended replacement, which seems to work for me, is the `drivetemp` kernel module, which will add SATA drive temperatures to the other sensor interfaces that the kernel already provides. Then after having installed the `lm-sensors` package, just running `sensors` will include SATA drive temps as well. So if you're on jammy or newer you need to switch.

https://bugs.launchpad.net/ubuntu/+source/hddtemp/+bug/1979320

I suggest to do the change also for existing releases, i.e. Focal.

**Comment by berendt** [comment]
Let's use sensors for this:

```
sudo apt-get install lm-sensors
Starts lm-sensors service
```
